name: "asciidisco"
profile:
  web: "http://asciidisco.com"
  twitter: "asciidisco"
  gravatar: "8a1b0077e61264c8a6cb5f2ee540d43b"
hasbeen:
  cities:
    - "Cologne"
    - "Hamburg"
    - "Berlin"
    - "London"
    - "Paris"
    - "Vienna"
    - "Wrocław"
    - "Warsaw"
    - "Amsterdam"
    - "Munich"
    - "Frankfurt"
    - "Den Haag"
    - "Lille"
    - "Lisbon"
    - "Stuttgart"
    - "Edinburgh"
    - "Bologna"
    - "Milan"
    - "Strasbourg"
    - "Freiburg im Breisgau"
    - "Koblenz"
    - "Trier"
    - "Luxembourg"
    - "Stockholm"
    - "Dusseldorf"
    - "Nuremberg"
    - "Bonn"
