name: "ben"
profile:
  web: "http://benjaminknofe.com"
  twitter: "bknofe"
  gravatar: "6aed6a0dfa09b46d6fbd5149eb56def8"
hasbeen:
  cities:
    - "Amiens"
    - "Berlin"
    - "Bradenton"
    - "Bremen"
    - "Copenhagen"
    - "Dortmund"
    - "Dresden"
    - "Gräfenroda"
    - "Hamburg"
    - "Hvide Sande"
    - "Jena"
    - "Jönköping"
    - "Karlsruhe"
    - "Kempten (Allgäu)"
    - "Leipzig"
    - "Lemvig"
    - "London"
    - "Malmö"
    - "Mundelsheim"
    - "Nuremberg"
    - "Prag"
    - "Stockholm"
    - "Stuttgart"
    - "Verona"
    - "Würzburg"
