name: "captainhagbard"
profile:
  web: "http://timoschilling.io"
  twitter: "captainhagbard"
  gravatar: "0d538506cb7d350250906243645c28d4"
hasbeen:
  cities:
    - "Berlin"
    - "Köln"
    - "Bochum"
    - "Dortmund"
    - "Wrocław"
    - "München"
    - "Amsterdam"
    - "Kraków"
    - "Salzburg"
