name: "Cashewkernchen"
profile:
  web: "http://ponywei.de"
  twitter: "casheeew"
  gravatar: ""
hasbeen:
  cities:
    - "Amsterdam"
    - "Berlin"
    - "Bonn"
    - "Chicago"
    - "Eindhoven"
    - "Hamburg"
    - "Köln"
    - "Las Vegas"
    - "London"
    - "Los Angeles"
    - "Maastricht"
    - "Mariposa"
    - "Marseille"
    - "Münster"
    - "Paris"
    - "San Francisco"
    - "Wien"
    - "Fuerteventura"
    - "Las Palmas"
    - "Yosemite"
    - "Warschau"
    - "Krakau"

