name: "Depone"
profile:
  web: "http://depone.net"
  twitter: "depone"
  gravatar: "0fccf147a884349076854bed0f954ef5"
hasbeen:
  cities:
    - "Karlsruhe"
    - "Stuttgart"
    - "Berlin"
    - "Hamburg"
    - "Tübingen"
    - "Nice"
    - "Minneapolis"
    - "Houston"
    - "London"
    - "Vienna"
    - "Amsterdam"
