name: "eimann"
profile:
  web: ""
  twitter: ""
  gravatar: ""
hasbeen:
  cities:
    - "Aachen"
    - "Abu Dhabi"
    - "Bejin"
    - "Berlin"
    - "Bonn"
    - "Boston"
    - "Calgary"
    - "Cologne"
    - "Dortmund"
    - "Essen"
    - "Edmonton"
    - "Hamburg"
    - "Kamen"
    - "Leipzig"
    - "Mailand"
    - "Montreal"
    - "Moskau"
    - "Mountain View"
    - "New York"
    - "Nice"
    - "Oslo"
    - "Ottawa"
    - "Paris"
    - "Prague"
    - "San Jose"
    - "Santa Clara"
    - "Seoul"
    - "Singapore"
    - "St. Augustin"
    - "Toronto"
    - "Vancouver"
    - "Vienna"
