name: "geekQ"
profile:
  web: "http://www.mobile-web-consulting.de"
  twitter: "enterprise_geek"
  gravatar: "e5536e38257a6ca81a0476ee928d237f"
hasbeen:
  cities:
    - "Челябинск"
    - "Москва"
    - "Миасс"
    - "Большие Харлуши"
    - "Санкт-Петербург"
    - "Düsseldorf"
    - "Cologne"
    - "Karlsruhe"
    - "Ettlingen"
    - "Frankfurt am Main"
    - "Schwalbach am Taunus"
    - "Berlin"
    - "Prague"
    - "London"
    - "Paris"
    - "Barcelona"
    - "Vienna"
    - "New York"
    - "Albany (New York)"
    - "Brussels"
    - "Amsterdam"
    - "Renesse"
    - "Munich"
    - "Potsdam"
    - "Lloret de Mar"
    - "Lanzarote"
    - "Ialysos"
    - "Karpathos"
    - "Rome"
    - "Venice"
    - "Westkapelle"
    - "Schleswig"
    - "Zürich"

