name: "Koehr"
profile:
  web: "http://koehr.in"
  twitter: "nkoehring"
  gravatar: "e224af035f8d297bcb715c192edcd189"
hasbeen:
  cities:
    - "Berlin"
    - "Leipzig"
    - "London"
    - "Prag"
    - "Wels"
    - "Wien"
    - "Dresden"
    - "Hamburg"
    - "München"
    - "Erfurt"
    - "Köln"
    - "Bonn"
