name: "lx4r"
profile:
  web: "https://l3r.de"
  twitter: "lx4r"
  gravatar: "b63e18496881cc13b0a0567bbc6cc185"
hasbeen:
  cities:
    - "Augsburg"
    - "Berlin"
    - "Hamburg"
    - "München"
    - "Nürnberg"
    - "Wyk auf Föhr"
    - "Wien"
    - "Kopenhagen"
    - "Lissabon"
    - "Porto"
    - "Ibiza"
    - "Sankt Petersburg"
    - "Barcelona"
    - "Paris"
    - "Istanbul"
    - "New York"
    - "Chicago"
    - "Boston"
