name: "Maria"
profile:
  web: "http://marianowak.de"
  twitter: ""
  gravatar: "c0855061d83500fffab37d41855a841b"
hasbeen:
  cities:
    - "Cologne"
    - "Hamburg"
    - "Oelsnitz"
    - "Berlin"
    - "Rostock"
    - "Munich"
    - "Potsdam"
    - "Weimar"
    - "Dresden" 
    - "Bangkok"
    - "Ko Tao"
    - "Shanghai"
    - "Wuxi"
    - "Suzhou"
    - "Beijing"
    - "Changzhou"
    - "Prague"
    - "London"
    - "Manchester"
    - "Paris"
    - "Barcelona"
    - "Moraira"
    - "Venice"
    - "Firenze"
    - "Pisa"
    - "Krakow"
    - "Sutomore"
    - "Bodrum"
    - "Gran Canaria"
    - "Brussels"
    - "Amsterdam"
    - "Ponta Delgada"
    - {"Curahuasi": "Diospi Suyana, Curahuasi"}
    - "Cusco"
    - "Ollantaytambo"
    - "Pisac"
    - "Las Vegas"
    - "San Francisco"
    - "Los Angeles"
