name: "PJ Kelly"
profile:
  web: "http://crushlovely.com"
  twitter: "_pjkelly"
  gravatar: "dd8e1454b92cc93c479caca4beadf09c"
hasbeen:
  cities:
    - "Akumal"
    - "Amsterdam"
    - "Ann Arbor"
    - "Banff"
    - "Berkeley"
    - "Boston"
    - "Chicago"
    - "Cincinatti"
    - "Cleveland"
    - "Dallas"
    - "Denver"
    - "Ensenada"
    - "Evanston"
    - "Hong Kong"
    - "Las Vegas"
    - "London"
    - "Los Angeles"
    - "Montreux"
    - "New Orleans"
    - "New York"
    - "Orlando"
    - "Perugia"
    - "Philadelphia"
    - "Phoenix"
    - "Pittsburgh"
    - "Portland"
    - "Puerto Nuevo"
    - "Rochester"
    - "Rome"
    - "San Francisco"
    - "Taipei"
    - "The Hague"
    - "Tijuana"
    - "Toronto"
    - "Zhanghua"