name: "purzel"
profile:
  web: "http://wollenzin.de"
  twitter: "purzei"
  gravatar: "8784d7c66ce0f292bc5d4ebc143a2569"
hasbeen:
  cities:
    - "Cologne"
    - "Munich"
    - "Berlin"
    - "Bonn"
    - "Hamburg"
    - "Dublin"
    - "Frankfurt a.M."
    - "London"
    - "Stuttgart"
    - "Augsburg"
    - "Hvide Sande"
    - "Fulda"
    - "Bochum"
    - "Maastricht"
    - "Roermond"
    - "Saarbruecken"
    - "Emden
    - "Flensburg"
    - "Kiel"
    - "Brighton"
    - "Trim"
