name: "ReneVolution"
profile:
  web: "http://www.sparklingstudio.de"
  twitter: "sparklingstudio"
  gravatar: "e590556cd6efce7b1dafb5fd4e6630c0"
hasbeen:
  cities:
    - "Cologne"
    - "Munich"
    - "Hamburg"
    - "Stuttgart"
    - "Berlin"
    - "Prague"
    - "Paris"
    - "London"
    - "Washington D.C."
    - "Philadelphia"
    - "New York"
    - "Buenos Aires"
    - "Gran Canaria"
    - "Tenerife"
    - "Dublin"
    - "Amsterdam"
    - "Domburg (NL)"
