name: "Skade"
profile:
  web: "http://asquera.de"
  twitter: "argorak"
  email: "florian.gilcher@asquera.de"
hasbeen:
  cities:
    - "Speyer"
    - "Hamburg"
    - "Berlin"
    - "Köln"
    - "Buenos Aires"
    - "Lobatse"
    - "Gaborone"
    - "St. John's"
    - "Amsterdam"
    - "Copenhagen"
    - "Sophia-Antipolis"
    - "Leipzig"
    - "Vienna"
    - "Dublin"
    - "Tokyo"
    - "Toronto"
    - "Niagara Falls"
    - "Kasane"
    - "Livingstone"
    - "Paris"
    - "Nice"
    - "Marrakesh"
    - "Santa Cruz de Tenerife"
    - "Stockholm"
    - "Turku"
    - "Helsinki"
    - "Barcelona"
    - "Marseille"
    - "Reims"
    - "Lisboa"
    - "Faro"
    - "Ghanzi"
    - "Montreal"
    - "Québec"
    - "Prague"
    - "Wrocław"
    - "Poznan"
    - "Kraków"