name: "Skade"
profile:
  web: "http://asquera.de"
  twitter: "argorak"
  email: "florian.gilcher@asquera.de"
hasbeen:
  cities:
    - "Speyer"
    - "Hamburg"
    - "Berlin"
    - "Köln"
    - "Buenos Aires"
    - "Lobatse"
    - "Gaborone"
    - "St. John's"
    - "Amsterdam"
    - "Copenhagen"
    - "Sophia-Antipolis"
