name: "tisba"
profile:
  web: "http://tisba.de"
  twitter: "tisba"
  gravatar: "5a342a41b386d3e37a1ed6d2232e4b87"
hasbeen:
  cities:
    - "Cologne"
    - "Munich"
    - "Berlin"
    - "Leipzig"
    - "Hamburg"
    - "Bangkok"
    - "Shanghai"
    - "Prague"
    - "Paris"
    - "Brussels"
    - "Beijing"
    - "Ho Chi Minh City"
    - "Singapore"
    - "Kuala Lumpur"
